[versions]
kotlin = "2.1.20"
kotlinx-browser = "0.3"
kotlinx-serialization = "1.8.1"
markdown = "0.7.3"

[libraries]
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser-wasm-js", version.ref = "kotlinx-browser" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
markdown = { module = "org.jetbrains:markdown", version.ref = "markdown" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
